name: test-action
on:
  pull_request:
    branches: [master]
    types:
      - opened

jobs:
  test-endpoint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        uses: npm install
      - name: Run Test
        uses: npm run test